### ISSUE TITLE
JME rendering in a JavaFX application uses wrong pixel format causing wrong colors to be displayed

### ISSUE THREAD

**Issue by DannyJo** [empirephoenix/JME3-JFX#33] opened 2015-09-01 13:37 UTC
Looking in SceneProcessorCopyToImageView$TransfertImage.copyFrameBufferToImage() I can see that a FrameBuffer with Format.RGB8 is used, however the setPixels() method call uses PixelFormat.getByteBgraInstance().

**Comment by davidB** [comment] 2015-09-01 18:35
It's not a bug (or I guess the cause) in jME 3.0
rm.getRenderer().readFrameBuffer doesn't care about `fb.setColorBuffer(Format.RGB8)`,  the output format is hardcoded to bgra.

anyway, I keet it open to check it with 3.0 and 3.1 ASAP.

**Comment by DannyJo** [comment] 2015-09-01 22:00
I just checked it with 3.0.10 and it works fine, however it's with 3.1.0-SNAPSHOT it seems to break. I think I know a fix for that though but not sure if the fix will work in 3.0.10, need to test that first.

**Comment by jupake** [comment] 2016-04-21 14:18
Is this project still alive?

**Comment by empirephoenix** [comment] 2016-04-21 14:21
Yes, also I use the latest git version usually and cannot confirm this issue :)

**Comment by jupake** [comment] 2016-04-21 14:39
I will try the latest git version, thx.

**Comment by jupake** [comment] 2016-04-21 15:21
Ok, Im hitting the same error that DannyJo is having. Im also on 3.1-alpha5. 3.0 works perfectly.

**Comment by davidB** [comment] 2016-04-21 15:49
for 3.1-alpha5, we have to recompile, I'll create a branch. just need to
discuss how we maintain both branch and how to version them.
If you to test my fork and branch :

```
repositories {
  //...
    maven { url "https://jitpack.io" }
}

dependencies {
    //compile "com.jme3x:jfx:1.dev.2016-04-15_161534-442b7cc"
     compile "com.github.davidb:JME3-JFX:jogl-SNAPSHOT"
```
like in
https://github.com/davidB/ld35_shape_invaders/blob/master/build.gradle

**Comment by DannyJo** [comment] 2016-04-21 19:26
Sounds good. I think we need to come up with a way of versioning this for JME 3.1 but perhaps we just keep a different branch for the 3.1 compatible source and master for 3.0 for now. Once 3.1.0 is released we could perhaps merge the branch into master and make master compatible with 3.1.0

**Comment by empirephoenix** [comment] 2016-04-22 06:01
Hm ok now I kinda wonder, I use both JME and this from git master, and have no false colors.

**Comment by davidB** [comment] 2016-04-22 07:12
@empirephoenix , current source of master is compatible with both 3.0 and 3.1. but not the binary .class
mainly due to change from Abstract class to interface of Application,...

An other point, is that with a dedicated 3.1 branch, we'll be able to remove some code (reflexion / try/catch we introduce to support both).

**Comment by jupake** [comment] 2016-04-22 07:37
@empirephoenix Ok, so Ive tried the master branch and @davidB repo, but still the same problem. So now Im thinking the problem is on my side somewhere. Any pointers as to how I can debug what my problem is? I new to JavaFx and ImageViews. And JME in general. This is basically what Im doing:

```
        JmeForImageView jme = new JmeForImageView();
        jme.bind(imageview);

        jme.enqueue( (jmeApp) -> {
            // save a reference to the app
            controller.setWorldApp(jmeApp);
            controller.setupWorldScene(imageview);

            jmeApp.getContext().getSettings().setFrameRate(60);
            jmeApp.restart();
            return true;
        });
```

And then my setupWorldScene() does this:

```
public void setupWorldScene(ImageView imgview) {

        worldApp.enqueue( () -> {

            worldApp.getStateManager().attach(new CameraInputAppState());

            CameraInputDriver driver = new CameraInputDriver();
            driver.app = worldApp;
            driver.speed = 5.0f;
            CameraInputDriver.bindDefaults(imgview, driver);


            Sphere s = new Sphere(32, 32, 2.5f, false, true);
            Geometry g = new Geometry("box", s);

            Material mat = new Material(worldApp.getAssetManager(), "Common/MatDefs/Light/Lighting.j3md");
            mat.setBoolean("UseMaterialColors", true);
            mat.setColor("Diffuse", ColorRGBA.Yellow);

            g.setMaterial(mat);
            worldApp.getRootNode().attachChild(g);

            DirectionalLight sun = new DirectionalLight();
            sun.setDirection(new Vector3f(1f, 1f, -1f).normalizeLocal());
            sun.setColor(ColorRGBA.White);
            worldApp.getRootNode().addLight(sun);

            Camera cam = worldApp.getCamera();
            cam.setLocation(new Vector3f(0f, 0f, 20f));
            cam.lookAt(new Vector3f(0, 0, 0), Vector3f.UNIT_Y);

            return true;

        });
    }
```

And then I get this:

http://imgur.com/z200n7o

@DannyJo I agree. Before merging, you could branch from master and that will be the 3.0 compatibility branch and then after merge master becomes 3.1 compatible.

**Comment by davidB** [comment] 2016-04-22 12:09
I'll take a look at this bug.

**Comment by davidB** [comment] 2016-04-27 20:58
I push a fix (to optimize) on my fork/branch:

compile "com.github.davidb:JME3-JFX:jogl-SNAPSHOT"

@empirephoenix any preference for the group/name/version of the 3.1 branch to avoid conflict with 3.0 ?
When we agree I'll PR/merge my branch into this repo.

**Comment by empirephoenix** [comment] 2016-04-28 05:34
hm i would say lets make a legacy branch for 3.0 and continue with newest version on master

**Comment by davidB** [comment] 2016-04-28 07:04
May be we can also upgrade the major number to 2. then user of jme 3.0, that should used 1.+ as version number will not be impacted. and we'll be able to publish later update/fix on version 1.x for jme 3.0 users.
Are you OK ?
(I should be day-off tomorrow, so I could work on this.)

**Comment by empirephoenix** [comment] 2016-04-28 09:58
Hm yeah that should work fine and solves all maven related issues

**Comment by davidB** [comment] 2016-04-30 15:48
Should be fixed in version 2.+
Feel free to reopen.

**Closed by davidB** 2016-04-30 15:48 UTC
